name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit:
    name: unit test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Checkout project
        uses: actions/checkout@v3

      - name: Build and test
        run: zig build test
